### ISSUE TITLE
Use native vars with non-native fallback

### ISSUE THREAD

**Issue by modularcoder** [shospodarets/css-vars#3]
Hi, thanks for this lib.

I was wondering if there is a way to use native vars with fallback to non-native attribute.

So let's say this 

```
@include css-vars((
        --main-color: #000,
));

body {
       color: var(--main-color);
}
```

Will compile to this

body {
       color: #000,
       color: var(--main-color);
}

And if the browser will support css properties it will use the second value from variable, but if not it will fall-back to first condition.

Thanks

**Comment by modularcoder** [comment]
I've played a bit with the lib, seems this is not possible, because the return value of function
**var()** doesn't know about the condition name.

Other work around might be creating a separate function, like.

```
body {
    css-set(color, --main-color);
}
```

**Comment by shospodarets** [comment]
Yes, the double output is not something, what's possible using the current mixin.
The main idea of the solution is to follow the native CSS Custom Properties syntax as close, as possible.
For you idea you can take a look to http://cssnext.io/ / https://github.com/postcss/postcss-custom-properties ,
where such an output can be easily provided (not sure it's available/configurable out of the box).

**Comment by modularcoder** [comment]
@malyw yep, thanks for info!
