### ISSUE TITLE
What is the point of sass variables now that we have css vars?

### ISSUE THREAD

**Issue by erichaus** [shospodarets/css-vars#4]
I'm just trying to understand why I would even continue to use sass variables at all when it seems like native css variables are advantageous and supported...

**Comment by shospodarets** [comment]
Unfortunately, you still cannot use CSS Custom Variables everywhere.
Simple examples are media query values and colo functions https://github.com/postcss/postcss-color-function , which still are not implemented in the browsers
https://www.w3.org/TR/css-color-4/

**Comment by erichaus** [comment]
ah yes that is a huge disadvantage to not be able to use color functions yet :/ already ran into that
