### ISSUE TITLE
Documentation for .sass implementations

### ISSUE THREAD

**Issue by bmcminn** [shospodarets/css-vars#6]
Been dealing with SASS and it's lack of support for `:root` and came across this awesome library; So far I'm really digging it, but ran into a few other intrinsic limitations with the `.sass` syntax...

Namely: https://github.com/sass/sass/issues/1088

Through that thread I found a user comment (https://github.com/sass/sass/issues/1088#issuecomment-114522391) which mentioned the `map-merge` method which solves this issue nicely.

```sass
@import "[%PATH%]/css-vars/css-vars";

$rootvars: ()

$rootvars: map-merge($rootvars, ( '--sidebar-width': $sidebar-width ))
$rootvars: map-merge($rootvars, ( '--topnav-height': $topnav-height ))
$rootvars: map-merge($rootvars, ( '-moz-tab-size': 4 ))
$rootvars: map-merge($rootvars, ( 'tab-size': 4 ))

@include css-vars($rootvars)
```

This yields the cleanest way to manage the syntax for `.sass` files and thought this might help other people in a similar situation.

**Comment by shospodarets** [comment]
`map-merge` functionality is used in css-vars themselves:
https://github.com/malyw/css-vars/blob/master/css-vars.scss#L32

You can even put additional vars to the global map used in the library:
`map-merge($css-vars, ( '--sidebar-width': $sidebar-width ))` , 
so you can avoid `@include css-vars($rootvars)`.

Did you suggest to update the documentation (feel free to provide a PR in that case)
or you wanted to reference something else?

**Comment by bmcminn** [comment]
Mostly just documenting a workaround for peeps using `.SASS` syntax where multi-line map definitions are not allowed.

I'll look into a PR for the docs at some point, but for now this issue may help point people in the right direction.

**Comment by shospodarets** [comment]
Closing as inactive. @bmcminn feel free to reopen if you still have the use case and details
