### ISSUE TITLE
Assign Sassy Var with CSS property

### ISSUE THREAD

**Issue by carl-parrish** [shospodarets/css-vars#7]
Should I be able to do something like this?

```css
@include css-var ((
    --primary: black;
     ....
));

$primary:  var(--primary);
```
because right now it looks like I can't do things like. 
```css
background-color: fade-out(var(--primary), 0.2);
```

**Comment by shospodarets** [comment]
Looks like there was a lot of typos in your examples:
```
@include css-vars((
    --primary: black
));

body{
  background-color: fade-out(var(--primary), 0.2);
}
```
gives you:
```
body {
  background-color: rgba(0, 0, 0, 0.8);
}
```
but you are not supposed to mix the CSS and Sass variables this way.
In your case, you need to use plain Sass variables, as you apply the Sass function to it, which calculates the color build time. CSS variables are calculated real-time, and even thought css-vars will resolve it for you, when you try this examples with native CSS Custom Properties, it won't work.
So in your case, when you apply color functions, use plain Sass color variables.
Here is how you can apply this to native CSS Properties- https://twitter.com/malyw/status/1004332079440515073

**Comment by carl-parrish** [comment]
If I should be able to pass a CSS var to a function like fade-out() then I don't need the SASS style var. I was asking if I could assign a CSS var to a Sass var because I didn't think I could use a CSS var in a Sass function.
